// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Schedules.ActiveCounts
{
    /// <summary>
    /// Builds and executes requests for operations under \schedules\active-counts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActiveCountsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Schedules.ActiveCounts.ActiveCountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActiveCountsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/schedules/active-counts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Schedules.ActiveCounts.ActiveCountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActiveCountsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/schedules/active-counts", rawUrl)
        {
        }
        /// <summary>
        /// Active-schedule count per workflow for the org — powers the workflowslist &quot;N active schedules&quot; indicator. Declared before /{schedule_id} so theliteral path isn&apos;t captured as an id.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet200Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet200Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet401Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet403Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet500Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet200Response>(requestInfo, global::Soenneker.Sixtyfour.OpenApiClient.Models.ActiveScheduleCountsEndpointSchedulesActiveCountsGet200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Active-schedule count per workflow for the org — powers the workflowslist &quot;N active schedules&quot; indicator. Declared before /{schedule_id} so theliteral path isn&apos;t captured as an id.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Schedules.ActiveCounts.ActiveCountsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sixtyfour.OpenApiClient.Schedules.ActiveCounts.ActiveCountsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sixtyfour.OpenApiClient.Schedules.ActiveCounts.ActiveCountsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
