// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive.Item;
using Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive.Start;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive
{
    /// <summary>
    /// Builds and executes requests for operations under \workflows\interactive
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InteractiveRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The start property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive.Start.StartRequestBuilder Start
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Sixtyfour.OpenApiClient.workflows.interactive.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive.Item.WithJob_ItemRequestBuilder"/></returns>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive.Item.WithJob_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("job_id", position);
                return new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive.Item.WithJob_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive.InteractiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InteractiveRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/interactive", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive.InteractiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InteractiveRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/interactive", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
