// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.EnrichLinkedin
{
    /// <summary>
    /// Builds and executes requests for operations under \enrich-linkedin
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnrichLinkedinRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.EnrichLinkedin.EnrichLinkedinRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnrichLinkedinRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enrich-linkedin", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.EnrichLinkedin.EnrichLinkedinRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnrichLinkedinRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enrich-linkedin", rawUrl)
        {
        }
        /// <summary>
        /// Fetch a LinkedIn profile and extract structured fields in a single LLM call.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.EnrichLinkedin.EnrichLinkedinPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost402">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost429">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost500">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.EnrichLinkedin.EnrichLinkedinPostResponse?> PostAsync(global::Soenneker.Sixtyfour.OpenApiClient.Models.LinkedInEnrichRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.EnrichLinkedin.EnrichLinkedinPostResponse> PostAsync(global::Soenneker.Sixtyfour.OpenApiClient.Models.LinkedInEnrichRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost401.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost402.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost403.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost404.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost429.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Sixtyfour.OpenApiClient.Models.EnrichLinkedinEndpointEnrichLinkedinPost500.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Sixtyfour.OpenApiClient.EnrichLinkedin.EnrichLinkedinPostResponse>(requestInfo, global::Soenneker.Sixtyfour.OpenApiClient.EnrichLinkedin.EnrichLinkedinPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch a LinkedIn profile and extract structured fields in a single LLM call.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Sixtyfour.OpenApiClient.Models.LinkedInEnrichRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Sixtyfour.OpenApiClient.Models.LinkedInEnrichRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.EnrichLinkedin.EnrichLinkedinRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sixtyfour.OpenApiClient.EnrichLinkedin.EnrichLinkedinRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sixtyfour.OpenApiClient.EnrichLinkedin.EnrichLinkedinRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
