// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Search.DeepSearchStatus.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Search.DeepSearchStatus
{
    /// <summary>
    /// Builds and executes requests for operations under \search\deep-search-status
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeepSearchStatusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Sixtyfour.OpenApiClient.search.deepSearchStatus.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Search.DeepSearchStatus.Item.WithTask_ItemRequestBuilder"/></returns>
        public global::Soenneker.Sixtyfour.OpenApiClient.Search.DeepSearchStatus.Item.WithTask_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("task_id", position);
                return new global::Soenneker.Sixtyfour.OpenApiClient.Search.DeepSearchStatus.Item.WithTask_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Search.DeepSearchStatus.DeepSearchStatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeepSearchStatusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/deep-search-status", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Search.DeepSearchStatus.DeepSearchStatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeepSearchStatusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/deep-search-status", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
