// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk
{
    /// <summary>
    /// Builds and executes requests for operations under \find-phone-v2-bulk
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FindPhoneV2BulkRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FindPhoneV2BulkRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/find-phone-v2-bulk", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FindPhoneV2BulkRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/find-phone-v2-bulk", rawUrl)
        {
        }
        /// <summary>
        /// V2: Find phones with full waterfall stats.
        /// </summary>
        /// <returns>A <see cref="UntypedNode"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk500Error">When receiving a 500 status code</exception>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<UntypedNode?> PostAsync(global::Soenneker.Sixtyfour.OpenApiClient.Models.FindPhoneV2BulkRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<UntypedNode> PostAsync(global::Soenneker.Sixtyfour.OpenApiClient.Models.FindPhoneV2BulkRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk401Error.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk402Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk404Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk429Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2Bulk500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<UntypedNode>(requestInfo, UntypedNode.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// V2: Find phones with full waterfall stats.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Sixtyfour.OpenApiClient.Models.FindPhoneV2BulkRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Sixtyfour.OpenApiClient.Models.FindPhoneV2BulkRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2BulkRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        [Obsolete("")]
        public global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2BulkRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sixtyfour.OpenApiClient.FindPhoneV2Bulk.FindPhoneV2BulkRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
