// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Workflows.Run
{
    /// <summary>
    /// Builds and executes requests for operations under \workflows\run
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RunRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Run.RunRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/run?workflow_id={workflow_id}{&result_formats*,save_json*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Run.RunRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/run?workflow_id={workflow_id}{&result_formats*,save_json*}", rawUrl)
        {
        }
        /// <summary>
        /// Start a workflow run and return a job ID for tracking.Supports per-run spec overrides via `specs_override` and webhook input via`webhook_payload`. API-triggered `read_csv` workflows must provide`specs_override.resource_handle_id` from `/storage/csv/upload`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunStartedResponse"/></returns>
        /// <param name="body">JSON body for POST /workflows/run (workflow_id/save_json/etc. stay query params).</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost409Response">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunStartedResponse?> PostAsync(global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowBody body, Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Run.RunRequestBuilder.RunRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunStartedResponse> PostAsync(global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowBody body, Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Run.RunRequestBuilder.RunRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost401Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost403Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost404Response.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost409Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowWorkflowsRunPost500Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunStartedResponse>(requestInfo, global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunStartedResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Start a workflow run and return a job ID for tracking.Supports per-run spec overrides via `specs_override` and webhook input via`webhook_payload`. API-triggered `read_csv` workflows must provide`specs_override.resource_handle_id` from `/storage/csv/upload`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">JSON body for POST /workflows/run (workflow_id/save_json/etc. stay query params).</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowBody body, Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Run.RunRequestBuilder.RunRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Sixtyfour.OpenApiClient.Models.RunWorkflowBody body, Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Run.RunRequestBuilder.RunRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Run.RunRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Run.RunRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Run.RunRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Start a workflow run and return a job ID for tracking.Supports per-run spec overrides via `specs_override` and webhook input via`webhook_payload`. API-triggered `read_csv` workflows must provide`specs_override.resource_handle_id` from `/storage/csv/upload`.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RunRequestBuilderPostQueryParameters 
        {
            /// <summary>Result formats to save. Repeat the parameter for multiple values, e.g. result_formats=csv&amp;result_formats=ndjson.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("result_formats")]
            public string? ResultFormats { get; set; }
#nullable restore
#else
            [QueryParameter("result_formats")]
            public string ResultFormats { get; set; }
#endif
            /// <summary>Also save results as JSON</summary>
            [QueryParameter("save_json")]
            public bool? SaveJson { get; set; }
            /// <summary>Workflow ID to run</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("workflow_id")]
            public string? WorkflowId { get; set; }
#nullable restore
#else
            [QueryParameter("workflow_id")]
            public string WorkflowId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
