// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentSession : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agent_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgentName { get; set; }
#nullable restore
#else
        public string AgentName { get; set; }
#endif
        /// <summary>The agent_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgentType { get; set; }
#nullable restore
#else
        public string AgentType { get; set; }
#endif
        /// <summary>The cost_cents property</summary>
        public int? CostCents { get; set; }
        /// <summary>The ended_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndedAt { get; set; }
#nullable restore
#else
        public string EndedAt { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The parent_session_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentSessionId { get; set; }
#nullable restore
#else
        public string ParentSessionId { get; set; }
#endif
        /// <summary>The started_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartedAt { get; set; }
#nullable restore
#else
        public string StartedAt { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The task property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Task { get; set; }
#nullable restore
#else
        public string Task { get; set; }
#endif
        /// <summary>The turn_count property</summary>
        public int? TurnCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.AgentSession"/> and sets the default values.
        /// </summary>
        public AgentSession()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.AgentSession"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.AgentSession CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.AgentSession();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_name", n => { AgentName = n.GetStringValue(); } },
                { "agent_type", n => { AgentType = n.GetStringValue(); } },
                { "cost_cents", n => { CostCents = n.GetIntValue(); } },
                { "ended_at", n => { EndedAt = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "parent_session_id", n => { ParentSessionId = n.GetStringValue(); } },
                { "started_at", n => { StartedAt = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "task", n => { Task = n.GetStringValue(); } },
                { "turn_count", n => { TurnCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("agent_name", AgentName);
            writer.WriteStringValue("agent_type", AgentType);
            writer.WriteIntValue("cost_cents", CostCents);
            writer.WriteStringValue("ended_at", EndedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("parent_session_id", ParentSessionId);
            writer.WriteStringValue("started_at", StartedAt);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("task", Task);
            writer.WriteIntValue("turn_count", TurnCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
