// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApprovalRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The answers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Answers { get; set; }
#nullable restore
#else
        public UntypedNode Answers { get; set; }
#endif
        /// <summary>The approval_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApprovalId { get; set; }
#nullable restore
#else
        public string ApprovalId { get; set; }
#endif
        /// <summary>The approved property</summary>
        public bool? Approved { get; set; }
        /// <summary>The reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest.ApprovalRequest_reason? Reason { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest.ApprovalRequest_reason Reason { get; set; }
#endif
        /// <summary>The session_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest"/> and sets the default values.
        /// </summary>
        public ApprovalRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "answers", n => { Answers = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "approval_id", n => { ApprovalId = n.GetStringValue(); } },
                { "approved", n => { Approved = n.GetBoolValue(); } },
                { "reason", n => { Reason = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest.ApprovalRequest_reason>(global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest.ApprovalRequest_reason.CreateFromDiscriminatorValue); } },
                { "session_id", n => { SessionId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("answers", Answers);
            writer.WriteStringValue("approval_id", ApprovalId);
            writer.WriteBoolValue("approved", Approved);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest.ApprovalRequest_reason>("reason", Reason);
            writer.WriteStringValue("session_id", SessionId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest_reasonMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApprovalRequest_reason : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest_reasonMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest_reasonMember1? ApprovalRequestReasonMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest_reasonMember1 ApprovalRequestReasonMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest.ApprovalRequest_reason"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest.ApprovalRequest_reason CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest.ApprovalRequest_reason();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ApprovalRequestReasonMember1 = new global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest_reasonMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ApprovalRequestReasonMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ApprovalRequestReasonMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.ApprovalRequest_reasonMember1>(null, ApprovalRequestReasonMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
