// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>
    /// Metrics for a block execution.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BlockMetrics : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dataframe_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DataframeType { get; set; }
#nullable restore
#else
        public string DataframeType { get; set; }
#endif
        /// <summary>The processed_count property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_processed_count? ProcessedCount { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_processed_count ProcessedCount { get; set; }
#endif
        /// <summary>The row_count property</summary>
        public int? RowCount { get; set; }
        /// <summary>The total_count property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_total_count? TotalCount { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_total_count TotalCount { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics"/> and sets the default values.
        /// </summary>
        public BlockMetrics()
        {
            AdditionalData = new Dictionary<string, object>();
            DataframeType = "LEAD";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dataframe_type", n => { DataframeType = n.GetStringValue(); } },
                { "processed_count", n => { ProcessedCount = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_processed_count>(global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_processed_count.CreateFromDiscriminatorValue); } },
                { "row_count", n => { RowCount = n.GetIntValue(); } },
                { "total_count", n => { TotalCount = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_total_count>(global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_total_count.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("dataframe_type", DataframeType);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_processed_count>("processed_count", ProcessedCount);
            writer.WriteIntValue("row_count", RowCount);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_total_count>("total_count", TotalCount);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_processed_countMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BlockMetrics_processed_count : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_processed_countMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_processed_countMember1? BlockMetricsProcessedCountMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_processed_countMember1 BlockMetricsProcessedCountMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_processed_count"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_processed_count CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_processed_count();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.BlockMetricsProcessedCountMember1 = new global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_processed_countMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BlockMetricsProcessedCountMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BlockMetricsProcessedCountMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_processed_countMember1>(null, BlockMetricsProcessedCountMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_total_countMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BlockMetrics_total_count : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_total_countMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_total_countMember1? BlockMetricsTotalCountMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_total_countMember1 BlockMetricsTotalCountMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_total_count"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_total_count CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics.BlockMetrics_total_count();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.BlockMetricsTotalCountMember1 = new global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_total_countMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BlockMetricsTotalCountMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BlockMetricsTotalCountMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.BlockMetrics_total_countMember1>(null, BlockMetricsTotalCountMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
