// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The messages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_messages>? Messages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_messages> Messages { get; set; }
#endif
        /// <summary>The page_context property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.PageContext? PageContext { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.PageContext PageContext { get; set; }
#endif
        /// <summary>The page_data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? PageData { get; set; }
#nullable restore
#else
        public UntypedNode PageData { get; set; }
#endif
        /// <summary>The search_rerun property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequest? SearchRerun { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequest SearchRerun { get; set; }
#endif
        /// <summary>The session_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>The timezone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_timezone? Timezone { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_timezone Timezone { get; set; }
#endif
        /// <summary>The workflow_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_workflow_id? WorkflowId { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_workflow_id WorkflowId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest"/> and sets the default values.
        /// </summary>
        public ChatRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_messages>(global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_messages.CreateFromDiscriminatorValue)?.AsList(); } },
                { "page_context", n => { PageContext = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.PageContext>(global::Soenneker.Sixtyfour.OpenApiClient.Models.PageContext.CreateFromDiscriminatorValue); } },
                { "page_data", n => { PageData = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "search_rerun", n => { SearchRerun = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequest>(global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequest.CreateFromDiscriminatorValue); } },
                { "session_id", n => { SessionId = n.GetStringValue(); } },
                { "timezone", n => { Timezone = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_timezone>(global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_timezone.CreateFromDiscriminatorValue); } },
                { "workflow_id", n => { WorkflowId = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_workflow_id>(global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_workflow_id.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_messages>("messages", Messages);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.PageContext>("page_context", PageContext);
            writer.WriteObjectValue<UntypedNode>("page_data", PageData);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequest>("search_rerun", SearchRerun);
            writer.WriteStringValue("session_id", SessionId);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_timezone>("timezone", Timezone);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_workflow_id>("workflow_id", WorkflowId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_timezoneMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChatRequest_timezone : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_timezoneMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_timezoneMember1? ChatRequestTimezoneMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_timezoneMember1 ChatRequestTimezoneMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_timezone"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_timezone CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_timezone();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ChatRequestTimezoneMember1 = new global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_timezoneMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ChatRequestTimezoneMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ChatRequestTimezoneMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_timezoneMember1>(null, ChatRequestTimezoneMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_workflow_idMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChatRequest_workflow_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_workflow_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_workflow_idMember1? ChatRequestWorkflowIdMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_workflow_idMember1 ChatRequestWorkflowIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_workflow_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_workflow_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest.ChatRequest_workflow_id();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ChatRequestWorkflowIdMember1 = new global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_workflow_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ChatRequestWorkflowIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ChatRequestWorkflowIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.ChatRequest_workflow_idMember1>(null, ChatRequestWorkflowIdMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
