// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>When the first check runs. &apos;now&apos; checks every row as soon as the monitor exists. &apos;next_tick&apos; waits for the schedule: an hourly monitor first runs at the next :00 UTC, a daily one at the next 00:00 UTC. The response&apos;s next_run_times says exactly when.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateMonitorRequestFirstCheck
    {
        [EnumMember(Value = "now")]
        #pragma warning disable CS1591
        Now,
        #pragma warning restore CS1591
        [EnumMember(Value = "next_tick")]
        #pragma warning disable CS1591
        NextTick,
        #pragma warning restore CS1591
    }
}
