// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>Quality and cost tier for the research agent.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnrichLeadInfo_tier
    {
        [EnumMember(Value = "low")]
        #pragma warning disable CS1591
        Low,
        #pragma warning restore CS1591
        [EnumMember(Value = "medium")]
        #pragma warning disable CS1591
        Medium,
        #pragma warning restore CS1591
        [EnumMember(Value = "high")]
        #pragma warning disable CS1591
        High,
        #pragma warning restore CS1591
    }
}
