// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>
    /// Response describing supported filter-search DSL capabilities.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilterSearchCapabilitiesResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Server cache TTL for mapping-derived capabilities.</summary>
        public int? CacheTtlSeconds { get; set; }
        /// <summary>Unified per-field capabilities sorted alphabetically.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldCapability>? Fields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldCapability> Fields { get; set; }
#endif
        /// <summary>Epoch timestamp (ms) when these capabilities were derived.</summary>
        public int? GeneratedAtEpochMs { get; set; }
        /// <summary>Public dataset identifier for company direct-filter queries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IndexName { get; set; }
#nullable restore
#else
        public string IndexName { get; set; }
#endif
        /// <summary>Constraint values for guarded DSL validation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchLimits? Limits { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchLimits Limits { get; set; }
#endif
        /// <summary>Hash of mapping metadata used to derive this capability snapshot.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_mapping_hash? MappingHash { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_mapping_hash MappingHash { get; set; }
#endif
        /// <summary>Search mode these capabilities apply to.</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_mode? Mode { get; set; }
        /// <summary>Allowed nested.path values for nested query clauses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NestedPaths { get; set; }
#nullable restore
#else
        public List<string> NestedPaths { get; set; }
#endif
        /// <summary>Supported MongoDB-style operators for simple_filters input.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_simple_query_operators? SimpleQueryOperators { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_simple_query_operators SimpleQueryOperators { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse"/> and sets the default values.
        /// </summary>
        public FilterSearchCapabilitiesResponse()
        {
            AdditionalData = new Dictionary<string, object>();
            Mode = global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_mode.Company;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cache_ttl_seconds", n => { CacheTtlSeconds = n.GetIntValue(); } },
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldCapability>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldCapability.CreateFromDiscriminatorValue)?.AsList(); } },
                { "generated_at_epoch_ms", n => { GeneratedAtEpochMs = n.GetIntValue(); } },
                { "index_name", n => { IndexName = n.GetStringValue(); } },
                { "limits", n => { Limits = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchLimits>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchLimits.CreateFromDiscriminatorValue); } },
                { "mapping_hash", n => { MappingHash = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_mapping_hash>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_mapping_hash.CreateFromDiscriminatorValue); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_mode>(); } },
                { "nested_paths", n => { NestedPaths = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "simple_query_operators", n => { SimpleQueryOperators = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_simple_query_operators>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_simple_query_operators.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("cache_ttl_seconds", CacheTtlSeconds);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldCapability>("fields", Fields);
            writer.WriteIntValue("generated_at_epoch_ms", GeneratedAtEpochMs);
            writer.WriteStringValue("index_name", IndexName);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchLimits>("limits", Limits);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_mapping_hash>("mapping_hash", MappingHash);
            writer.WriteEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_mode>("mode", Mode);
            writer.WriteCollectionOfPrimitiveValues<string>("nested_paths", NestedPaths);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_simple_query_operators>("simple_query_operators", SimpleQueryOperators);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_mapping_hashMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FilterSearchCapabilitiesResponse_mapping_hash : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_mapping_hashMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_mapping_hashMember1? FilterSearchCapabilitiesResponseMappingHashMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_mapping_hashMember1 FilterSearchCapabilitiesResponseMappingHashMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_mapping_hash"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_mapping_hash CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_mapping_hash();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.FilterSearchCapabilitiesResponseMappingHashMember1 = new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_mapping_hashMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(FilterSearchCapabilitiesResponseMappingHashMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(FilterSearchCapabilitiesResponseMappingHashMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_mapping_hashMember1>(null, FilterSearchCapabilitiesResponseMappingHashMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_simple_query_operatorsMember1"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FilterSearchCapabilitiesResponse_simple_query_operators : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_simple_query_operatorsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_simple_query_operatorsMember1? FilterSearchCapabilitiesResponseSimpleQueryOperatorsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_simple_query_operatorsMember1 FilterSearchCapabilitiesResponseSimpleQueryOperatorsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_simple_query_operators"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_simple_query_operators CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse.FilterSearchCapabilitiesResponse_simple_query_operators();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.FilterSearchCapabilitiesResponseSimpleQueryOperatorsMember1 = new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_simple_query_operatorsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(FilterSearchCapabilitiesResponseSimpleQueryOperatorsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(FilterSearchCapabilitiesResponseSimpleQueryOperatorsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchCapabilitiesResponse_simple_query_operatorsMember1>(null, FilterSearchCapabilitiesResponseSimpleQueryOperatorsMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
