// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>
    /// Response for a completed filter search.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilterSearchResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Signed URL to download results as CSV.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CsvDownloadUrl { get; set; }
#nullable restore
#else
        public string CsvDownloadUrl { get; set; }
#endif
        /// <summary>Seconds until `next_cursor` expires.</summary>
        public int? CursorExpiresInSeconds { get; set; }
        /// <summary>Seconds until the download URLs expire.</summary>
        public int? DownloadExpiresInSeconds { get; set; }
        /// <summary>Legacy export count; always 0 for company direct-filter mode.</summary>
        public int? ExportedCount { get; set; }
        /// <summary>True when another page is available via `next_cursor`.</summary>
        public bool? HasMore { get; set; }
        /// <summary>Signed URL to download results as JSON.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JsonDownloadUrl { get; set; }
#nullable restore
#else
        public string JsonDownloadUrl { get; set; }
#endif
        /// <summary>Upper bound on pages based on max_results and page_size.</summary>
        public int? MaxPages { get; set; }
        /// <summary>Original natural-language query echoed verbatim, if any.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NaturalLanguageQuery { get; set; }
#nullable restore
#else
        public string NaturalLanguageQuery { get; set; }
#endif
        /// <summary>Cursor to fetch the next page; null when exhausted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextCursor { get; set; }
#nullable restore
#else
        public string NextCursor { get; set; }
#endif
        /// <summary>Number of results in this response page.</summary>
        public int? PageCount { get; set; }
        /// <summary>1-based page number (company pagination).</summary>
        public int? PageNumber { get; set; }
        /// <summary>Number of results per page (1-100).</summary>
        public int? PageSize { get; set; }
        /// <summary>Structured filter set echoed back; round-trippable into a follow-up request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse_parsed_query? ParsedQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse_parsed_query ParsedQuery { get; set; }
#endif
        /// <summary>Rows still available under max_results after this page.</summary>
        public int? RemainingResults { get; set; }
        /// <summary>Server-side request duration in milliseconds.</summary>
        public int? RequestDurationMs { get; set; }
        /// <summary>Legacy export handle. Empty for company direct-filter mode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceHandleId { get; set; }
#nullable restore
#else
        public string ResourceHandleId { get; set; }
#endif
        /// <summary>Rows returned for the current page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse_results>? Results { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse_results> Results { get; set; }
#endif
        /// <summary>Search history ID; reuse with /search/query or /search/export.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchId { get; set; }
#nullable restore
#else
        public string SearchId { get; set; }
#endif
        /// <summary>Total OpenSearch matches across pages (capped at 50000); people-mode only.</summary>
        public int? TotalAvailable { get; set; }
        /// <summary>Final total page count; omitted while `has_more` is true.</summary>
        public int? TotalPages { get; set; }
        /// <summary>Rows returned so far (cumulative for company pagination).</summary>
        public int? TotalResults { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse"/> and sets the default values.
        /// </summary>
        public FilterSearchResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "csv_download_url", n => { CsvDownloadUrl = n.GetStringValue(); } },
                { "cursor_expires_in_seconds", n => { CursorExpiresInSeconds = n.GetIntValue(); } },
                { "download_expires_in_seconds", n => { DownloadExpiresInSeconds = n.GetIntValue(); } },
                { "exported_count", n => { ExportedCount = n.GetIntValue(); } },
                { "has_more", n => { HasMore = n.GetBoolValue(); } },
                { "json_download_url", n => { JsonDownloadUrl = n.GetStringValue(); } },
                { "max_pages", n => { MaxPages = n.GetIntValue(); } },
                { "natural_language_query", n => { NaturalLanguageQuery = n.GetStringValue(); } },
                { "next_cursor", n => { NextCursor = n.GetStringValue(); } },
                { "page_count", n => { PageCount = n.GetIntValue(); } },
                { "page_number", n => { PageNumber = n.GetIntValue(); } },
                { "page_size", n => { PageSize = n.GetIntValue(); } },
                { "parsed_query", n => { ParsedQuery = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse_parsed_query>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse_parsed_query.CreateFromDiscriminatorValue); } },
                { "remaining_results", n => { RemainingResults = n.GetIntValue(); } },
                { "request_duration_ms", n => { RequestDurationMs = n.GetIntValue(); } },
                { "resource_handle_id", n => { ResourceHandleId = n.GetStringValue(); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse_results>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse_results.CreateFromDiscriminatorValue)?.AsList(); } },
                { "search_id", n => { SearchId = n.GetStringValue(); } },
                { "total_available", n => { TotalAvailable = n.GetIntValue(); } },
                { "total_pages", n => { TotalPages = n.GetIntValue(); } },
                { "total_results", n => { TotalResults = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("csv_download_url", CsvDownloadUrl);
            writer.WriteIntValue("cursor_expires_in_seconds", CursorExpiresInSeconds);
            writer.WriteIntValue("download_expires_in_seconds", DownloadExpiresInSeconds);
            writer.WriteIntValue("exported_count", ExportedCount);
            writer.WriteBoolValue("has_more", HasMore);
            writer.WriteStringValue("json_download_url", JsonDownloadUrl);
            writer.WriteIntValue("max_pages", MaxPages);
            writer.WriteStringValue("natural_language_query", NaturalLanguageQuery);
            writer.WriteStringValue("next_cursor", NextCursor);
            writer.WriteIntValue("page_count", PageCount);
            writer.WriteIntValue("page_number", PageNumber);
            writer.WriteIntValue("page_size", PageSize);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse_parsed_query>("parsed_query", ParsedQuery);
            writer.WriteIntValue("remaining_results", RemainingResults);
            writer.WriteIntValue("request_duration_ms", RequestDurationMs);
            writer.WriteStringValue("resource_handle_id", ResourceHandleId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterSearchResponse_results>("results", Results);
            writer.WriteStringValue("search_id", SearchId);
            writer.WriteIntValue("total_available", TotalAvailable);
            writer.WriteIntValue("total_pages", TotalPages);
            writer.WriteIntValue("total_results", TotalResults);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
