// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>
    /// Request for top values of a single field.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilterFieldValuesRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Canonical field path to aggregate values for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Field { get; set; }
#nullable restore
#else
        public string Field { get; set; }
#endif
        /// <summary>Raw OpenSearch DSL filters that scope the aggregation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestFilters? Filters { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestFilters Filters { get; set; }
#endif
        /// <summary>&quot;Search mode: &apos;people&apos; or &apos;company&apos;.&quot;</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestMode? Mode { get; set; }
        /// <summary>MongoDB-style filters that scope the aggregation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestSimpleFilters? SimpleFilters { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestSimpleFilters SimpleFilters { get; set; }
#endif
        /// <summary>Maximum number of top values to return.</summary>
        public int? TopK { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequest"/> and sets the default values.
        /// </summary>
        public FilterFieldValuesRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            TopK = 25;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "field", n => { Field = n.GetStringValue(); } },
                { "filters", n => { Filters = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestFilters>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestFilters.CreateFromDiscriminatorValue); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestMode>(); } },
                { "simple_filters", n => { SimpleFilters = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestSimpleFilters>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestSimpleFilters.CreateFromDiscriminatorValue); } },
                { "top_k", n => { TopK = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("field", Field);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestFilters>("filters", Filters);
            writer.WriteEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestMode>("mode", Mode);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesRequestSimpleFilters>("simple_filters", SimpleFilters);
            writer.WriteIntValue("top_k", TopK);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
