// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>
    /// Top values response for one field.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilterFieldValuesResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Underlying field used for the terms aggregation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_aggregation_field? AggregationField { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_aggregation_field AggregationField { get; set; }
#endif
        /// <summary>Canonical field path used for aggregation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanonicalField { get; set; }
#nullable restore
#else
        public string CanonicalField { get; set; }
#endif
        /// <summary>Field requested by the caller.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Field { get; set; }
#nullable restore
#else
        public string Field { get; set; }
#endif
        /// <summary>Search mode: &apos;people&apos; or &apos;company&apos;.</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_mode? Mode { get; set; }
        /// <summary>Nested path, if any.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_nested_path? NestedPath { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_nested_path NestedPath { get; set; }
#endif
        /// <summary>Recommended for simple exact-match queries over its nested counterpart.</summary>
        public bool? PreferredForExactMatch { get; set; }
        /// <summary>Other field paths representing the same concept (e.g. flat counterpart of nested).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RelatedFields { get; set; }
#nullable restore
#else
        public List<string> RelatedFields { get; set; }
#endif
        /// <summary>Server-side request duration in milliseconds.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_request_duration_ms? RequestDurationMs { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_request_duration_ms RequestDurationMs { get; set; }
#endif
        /// <summary>Whether the response includes deterministic filter snippets.</summary>
        public bool? SupportsExactFilterSnippet { get; set; }
        /// <summary>Whether this field supports top-values aggregation.</summary>
        public bool? SupportsTopValues { get; set; }
        /// <summary>Total documents matched by the scoped query.</summary>
        public int? TotalScopedDocuments { get; set; }
        /// <summary>Top values ordered by count.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesValue>? Values { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesValue> Values { get; set; }
#endif
        /// <summary>Aggregation target type (keyword, long, etc.).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ValueType { get; set; }
#nullable restore
#else
        public string ValueType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse"/> and sets the default values.
        /// </summary>
        public FilterFieldValuesResponse()
        {
            AdditionalData = new Dictionary<string, object>();
            Mode = global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_mode.Company;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aggregation_field", n => { AggregationField = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_aggregation_field>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_aggregation_field.CreateFromDiscriminatorValue); } },
                { "canonical_field", n => { CanonicalField = n.GetStringValue(); } },
                { "field", n => { Field = n.GetStringValue(); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_mode>(); } },
                { "nested_path", n => { NestedPath = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_nested_path>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_nested_path.CreateFromDiscriminatorValue); } },
                { "preferred_for_exact_match", n => { PreferredForExactMatch = n.GetBoolValue(); } },
                { "related_fields", n => { RelatedFields = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "request_duration_ms", n => { RequestDurationMs = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_request_duration_ms>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_request_duration_ms.CreateFromDiscriminatorValue); } },
                { "supports_exact_filter_snippet", n => { SupportsExactFilterSnippet = n.GetBoolValue(); } },
                { "supports_top_values", n => { SupportsTopValues = n.GetBoolValue(); } },
                { "total_scoped_documents", n => { TotalScopedDocuments = n.GetIntValue(); } },
                { "value_type", n => { ValueType = n.GetStringValue(); } },
                { "values", n => { Values = n.GetCollectionOfObjectValues<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesValue>(global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesValue.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_aggregation_field>("aggregation_field", AggregationField);
            writer.WriteStringValue("canonical_field", CanonicalField);
            writer.WriteStringValue("field", Field);
            writer.WriteEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_mode>("mode", Mode);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_nested_path>("nested_path", NestedPath);
            writer.WriteBoolValue("preferred_for_exact_match", PreferredForExactMatch);
            writer.WriteCollectionOfPrimitiveValues<string>("related_fields", RelatedFields);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_request_duration_ms>("request_duration_ms", RequestDurationMs);
            writer.WriteBoolValue("supports_exact_filter_snippet", SupportsExactFilterSnippet);
            writer.WriteBoolValue("supports_top_values", SupportsTopValues);
            writer.WriteIntValue("total_scoped_documents", TotalScopedDocuments);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesValue>("values", Values);
            writer.WriteStringValue("value_type", ValueType);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_aggregation_fieldMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FilterFieldValuesResponse_aggregation_field : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_aggregation_fieldMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_aggregation_fieldMember1? FilterFieldValuesResponseAggregationFieldMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_aggregation_fieldMember1 FilterFieldValuesResponseAggregationFieldMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_aggregation_field"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_aggregation_field CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_aggregation_field();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.FilterFieldValuesResponseAggregationFieldMember1 = new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_aggregation_fieldMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(FilterFieldValuesResponseAggregationFieldMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(FilterFieldValuesResponseAggregationFieldMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_aggregation_fieldMember1>(null, FilterFieldValuesResponseAggregationFieldMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_nested_pathMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FilterFieldValuesResponse_nested_path : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_nested_pathMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_nested_pathMember1? FilterFieldValuesResponseNestedPathMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_nested_pathMember1 FilterFieldValuesResponseNestedPathMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_nested_path"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_nested_path CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_nested_path();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.FilterFieldValuesResponseNestedPathMember1 = new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_nested_pathMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(FilterFieldValuesResponseNestedPathMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(FilterFieldValuesResponseNestedPathMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_nested_pathMember1>(null, FilterFieldValuesResponseNestedPathMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_request_duration_msMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FilterFieldValuesResponse_request_duration_ms : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_request_duration_msMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_request_duration_msMember1? FilterFieldValuesResponseRequestDurationMsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_request_duration_msMember1 FilterFieldValuesResponseRequestDurationMsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_request_duration_ms"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_request_duration_ms CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse.FilterFieldValuesResponse_request_duration_ms();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.FilterFieldValuesResponseRequestDurationMsMember1 = new global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_request_duration_msMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(FilterFieldValuesResponseRequestDurationMsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(FilterFieldValuesResponseRequestDurationMsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.FilterFieldValuesResponse_request_duration_msMember1>(null, FilterFieldValuesResponseRequestDurationMsMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
