// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GenerateSearchTitleRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The entityMode property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest_entityMode? EntityMode { get; set; }
        /// <summary>The parsedQuery property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest_parsedQuery? ParsedQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest_parsedQuery ParsedQuery { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest"/> and sets the default values.
        /// </summary>
        public GenerateSearchTitleRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            EntityMode = global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest_entityMode.People;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entityMode", n => { EntityMode = n.GetEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest_entityMode>(); } },
                { "parsedQuery", n => { ParsedQuery = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest_parsedQuery>(global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest_parsedQuery.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest_entityMode>("entityMode", EntityMode);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.GenerateSearchTitleRequest_parsedQuery>("parsedQuery", ParsedQuery);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
