// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetLinkedInRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The include_fresh property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest.GetLinkedInRequest_include_fresh? IncludeFresh { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest.GetLinkedInRequest_include_fresh IncludeFresh { get; set; }
#endif
        /// <summary>The linkedin_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkedinUrl { get; set; }
#nullable restore
#else
        public string LinkedinUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest"/> and sets the default values.
        /// </summary>
        public GetLinkedInRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "include_fresh", n => { IncludeFresh = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest.GetLinkedInRequest_include_fresh>(global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest.GetLinkedInRequest_include_fresh.CreateFromDiscriminatorValue); } },
                { "linkedin_url", n => { LinkedinUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest.GetLinkedInRequest_include_fresh>("include_fresh", IncludeFresh);
            writer.WriteStringValue("linkedin_url", LinkedinUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest_include_freshMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetLinkedInRequest_include_fresh : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest_include_freshMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest_include_freshMember1? GetLinkedInRequestIncludeFreshMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest_include_freshMember1 GetLinkedInRequestIncludeFreshMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest.GetLinkedInRequest_include_fresh"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest.GetLinkedInRequest_include_fresh CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest.GetLinkedInRequest_include_fresh();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.GetLinkedInRequestIncludeFreshMember1 = new global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest_include_freshMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GetLinkedInRequestIncludeFreshMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GetLinkedInRequestIncludeFreshMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.GetLinkedInRequest_include_freshMember1>(null, GetLinkedInRequestIncludeFreshMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
