// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>`completed` means the PDF is downloadable; `superseded` means the workspace changed and a newer job replaced this one.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ReportJobStatus
    {
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "running")]
        #pragma warning disable CS1591
        Running,
        #pragma warning restore CS1591
        [EnumMember(Value = "completed")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "superseded")]
        #pragma warning disable CS1591
        Superseded,
        #pragma warning restore CS1591
    }
}
