// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>
    /// Unified search query request — replaces both /start-filter-search and /browse.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchQueryRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Opaque pagination cursor returned by a previous response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cursor { get; set; }
#nullable restore
#else
        public string Cursor { get; set; }
#endif
        /// <summary>Inline identifiers to exclude from results, applied as a post-filter. People mode: LinkedIn public IDs or profile URLs. Company mode: numeric LinkedIn company IDs, company URLs/slugs, or exact website domains (values that resolve to no or multiple companies are ignored). Max 1000 for API requests, 50000 for platform requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludeEntityIds { get; set; }
#nullable restore
#else
        public List<string> ExcludeEntityIds { get; set; }
#endif
        /// <summary>Saved exclusion-list IDs to apply as a post-filter. Each list&apos;s entity type must match the search mode (person lists for people searches, company lists for company searches). Max 5 (10 for organizations with extended exclusion limits).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludeListIds { get; set; }
#nullable restore
#else
        public List<string> ExcludeListIds { get; set; }
#endif
        /// <summary>People-mode inline identifiers to exclude from results, applied as a post-filter. Accepts LinkedIn public IDs or profile URLs. For company searches, use `exclude_entity_ids`. Max 1000 for API requests, 50000 for platform requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludePublicIds { get; set; }
#nullable restore
#else
        public List<string> ExcludePublicIds { get; set; }
#endif
        /// <summary>Expand a `parsed_query` location by radius. Off by default: only the `query` (NL) branch expanded before, so existing callers keep their result sets. `location_expansion_enabled` still gates the NL branch.</summary>
        public bool? ExpandStructuredLocation { get; set; }
        /// <summary>Raw OpenSearch DSL filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestFiltersProperty? Filters { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestFiltersProperty Filters { get; set; }
#endif
        /// <summary>Company-mode page offset for page-numbered navigation (mirrors OpenSearch `from`). Offset pages return no cursor and are not persisted to history; page one (offset 0 or omitted) behaves exactly as before. People mode rejects this field.</summary>
        public int? FromOffset { get; set; }
        /// <summary>Expand the location filter to nearby areas via PostGIS radius on the `query` (NL) branch. For `parsed_query`, use `expand_structured_location`.</summary>
        public bool? LocationExpansionEnabled { get; set; }
        /// <summary>Radius (miles) for PostGIS location expansion. Ignored when expansion is disabled.</summary>
        public int? LocationExpansionRadiusMiles { get; set; }
        /// <summary>Maximum number of results to return across pages. Omit to get the default for your credential: 1000 for API keys, the platform ceiling for signed-in sessions. Values above your ceiling are rejected.</summary>
        public int? MaxResults { get; set; }
        /// <summary>Search mode; inferred from DB when using `search_id`.</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestMode? Mode { get; set; }
        /// <summary>Return raw OpenSearch rows or canonical workflow LEAD/COMPANY rows. The selected shape is retained by cursor continuations.</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestOutputShape? OutputShape { get; set; }
        /// <summary>Maximum number of results per page (1-100). Pages may contain fewer rows while more results remain (e.g. with exclusion filtering); rely on `has_more`/`next_cursor`, never on page fullness.</summary>
        public int? PageSize { get; set; }
        /// <summary>Structured filter set returned by a previous search.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestParsedQueryProperty? ParsedQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestParsedQueryProperty ParsedQuery { get; set; }
#endif
        /// <summary>Set false to skip the canonical search-history write for this search (e.g. a page load that replays a search another surface already recorded). Replays via search_id never write history regardless.</summary>
        public bool? PersistHistory { get; set; }
        /// <summary>Natural-language query. Mutually exclusive with simple_filters / filters / parsed_query / search_id. Supported for people and company search.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>Display label stored with a structured search. It does not affect the query or results. Oversized labels are truncated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QueryLabel { get; set; }
#nullable restore
#else
        public string QueryLabel { get; set; }
#endif
        /// <summary>Search history ID returned by a previous search. Replays only the query shape; pass exclusions again on this request if they should apply.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchId { get; set; }
#nullable restore
#else
        public string SearchId { get; set; }
#endif
        /// <summary>Platform-only name -&gt; company ID map from autocomplete. Each pair is verified against the company index before use; unverified pairs fall back to name resolution. Disambiguates companies sharing a name. Excess hints are ignored; parsed-query name matching still applies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestSelectedCompanyIdsProperty? SelectedCompanyIds { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestSelectedCompanyIdsProperty SelectedCompanyIds { get; set; }
#endif
        /// <summary>Platform-only exact company selections. The backend resolves names to company IDs instead of trusting client-supplied OpenSearch IDs. Excess hints are ignored; parsed-query name matching still applies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SelectedCompanyNames { get; set; }
#nullable restore
#else
        public List<string> SelectedCompanyNames { get; set; }
#endif
        /// <summary>MongoDB-style filters; the API translates them to DSL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestSimpleFiltersProperty? SimpleFilters { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestSimpleFiltersProperty SimpleFilters { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequest"/> and sets the default values.
        /// </summary>
        public SearchQueryRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            ExpandStructuredLocation = false;
            LocationExpansionEnabled = true;
            LocationExpansionRadiusMiles = 10;
            PageSize = 10;
            PersistHistory = true;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cursor", n => { Cursor = n.GetStringValue(); } },
                { "exclude_entity_ids", n => { ExcludeEntityIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "exclude_list_ids", n => { ExcludeListIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "exclude_public_ids", n => { ExcludePublicIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "expand_structured_location", n => { ExpandStructuredLocation = n.GetBoolValue(); } },
                { "filters", n => { Filters = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestFiltersProperty>(global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestFiltersProperty.CreateFromDiscriminatorValue); } },
                { "from_offset", n => { FromOffset = n.GetIntValue(); } },
                { "location_expansion_enabled", n => { LocationExpansionEnabled = n.GetBoolValue(); } },
                { "location_expansion_radius_miles", n => { LocationExpansionRadiusMiles = n.GetIntValue(); } },
                { "max_results", n => { MaxResults = n.GetIntValue(); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestMode>(); } },
                { "output_shape", n => { OutputShape = n.GetEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestOutputShape>(); } },
                { "page_size", n => { PageSize = n.GetIntValue(); } },
                { "parsed_query", n => { ParsedQuery = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestParsedQueryProperty>(global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestParsedQueryProperty.CreateFromDiscriminatorValue); } },
                { "persist_history", n => { PersistHistory = n.GetBoolValue(); } },
                { "query", n => { Query = n.GetStringValue(); } },
                { "query_label", n => { QueryLabel = n.GetStringValue(); } },
                { "search_id", n => { SearchId = n.GetStringValue(); } },
                { "selected_company_ids", n => { SelectedCompanyIds = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestSelectedCompanyIdsProperty>(global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestSelectedCompanyIdsProperty.CreateFromDiscriminatorValue); } },
                { "selected_company_names", n => { SelectedCompanyNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "simple_filters", n => { SimpleFilters = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestSimpleFiltersProperty>(global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestSimpleFiltersProperty.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cursor", Cursor);
            writer.WriteCollectionOfPrimitiveValues<string>("exclude_entity_ids", ExcludeEntityIds);
            writer.WriteCollectionOfPrimitiveValues<string>("exclude_list_ids", ExcludeListIds);
            writer.WriteCollectionOfPrimitiveValues<string>("exclude_public_ids", ExcludePublicIds);
            writer.WriteBoolValue("expand_structured_location", ExpandStructuredLocation);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestFiltersProperty>("filters", Filters);
            writer.WriteIntValue("from_offset", FromOffset);
            writer.WriteBoolValue("location_expansion_enabled", LocationExpansionEnabled);
            writer.WriteIntValue("location_expansion_radius_miles", LocationExpansionRadiusMiles);
            writer.WriteIntValue("max_results", MaxResults);
            writer.WriteEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestMode>("mode", Mode);
            writer.WriteEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestOutputShape>("output_shape", OutputShape);
            writer.WriteIntValue("page_size", PageSize);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestParsedQueryProperty>("parsed_query", ParsedQuery);
            writer.WriteBoolValue("persist_history", PersistHistory);
            writer.WriteStringValue("query", Query);
            writer.WriteStringValue("query_label", QueryLabel);
            writer.WriteStringValue("search_id", SearchId);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestSelectedCompanyIdsProperty>("selected_company_ids", SelectedCompanyIds);
            writer.WriteCollectionOfPrimitiveValues<string>("selected_company_names", SelectedCompanyNames);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchQueryRequestSimpleFiltersProperty>("simple_filters", SimpleFilters);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
