// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchRerunRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The exclude_public_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequestExcludePublicIds? ExcludePublicIds { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequestExcludePublicIds ExcludePublicIds { get; set; }
#endif
        /// <summary>The filters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequestFiltersProperty? Filters { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequestFiltersProperty Filters { get; set; }
#endif
        /// <summary>The location_expansion_enabled property</summary>
        public bool? LocationExpansionEnabled { get; set; }
        /// <summary>The location_expansion_radius_miles property</summary>
        public int? LocationExpansionRadiusMiles { get; set; }
        /// <summary>The search_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchId { get; set; }
#nullable restore
#else
        public string SearchId { get; set; }
#endif
        /// <summary>The search_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchType { get; set; }
#nullable restore
#else
        public string SearchType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequest"/> and sets the default values.
        /// </summary>
        public SearchRerunRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            LocationExpansionEnabled = true;
            LocationExpansionRadiusMiles = 10;
            SearchType = "people";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "exclude_public_ids", n => { ExcludePublicIds = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequestExcludePublicIds>(global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequestExcludePublicIds.CreateFromDiscriminatorValue); } },
                { "filters", n => { Filters = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequestFiltersProperty>(global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequestFiltersProperty.CreateFromDiscriminatorValue); } },
                { "location_expansion_enabled", n => { LocationExpansionEnabled = n.GetBoolValue(); } },
                { "location_expansion_radius_miles", n => { LocationExpansionRadiusMiles = n.GetIntValue(); } },
                { "search_id", n => { SearchId = n.GetStringValue(); } },
                { "search_type", n => { SearchType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequestExcludePublicIds>("exclude_public_ids", ExcludePublicIds);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchRerunRequestFiltersProperty>("filters", Filters);
            writer.WriteBoolValue("location_expansion_enabled", LocationExpansionEnabled);
            writer.WriteIntValue("location_expansion_radius_miles", LocationExpansionRadiusMiles);
            writer.WriteStringValue("search_id", SearchId);
            writer.WriteStringValue("search_type", SearchType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
