// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>
    /// Request to start a filter-based search (no LLM step).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StartFilterSearchRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Opaque pagination cursor returned by a previous response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cursor { get; set; }
#nullable restore
#else
        public string Cursor { get; set; }
#endif
        /// <summary>Raw OpenSearch DSL filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestFilters? Filters { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestFilters Filters { get; set; }
#endif
        /// <summary>Maximum number of results to return across pages.</summary>
        public int? MaxResults { get; set; }
        /// <summary>&quot;Search mode: &apos;people&apos; or &apos;company&apos;.&quot;</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestMode? Mode { get; set; }
        /// <summary>Maximum number of results per page (1-100). Pages may contain fewer rows while more results remain (e.g. with exclusion filtering); rely on `has_more`/`next_cursor`, never on page fullness.</summary>
        public int? PageSize { get; set; }
        /// <summary>Also save results as JSON in addition to CSV.</summary>
        public bool? SaveJson { get; set; }
        /// <summary>MongoDB-style filters that the API translates to DSL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestSimpleFilters? SimpleFilters { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestSimpleFilters SimpleFilters { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequest"/> and sets the default values.
        /// </summary>
        public StartFilterSearchRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            MaxResults = 1000;
            PageSize = 10;
            SaveJson = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cursor", n => { Cursor = n.GetStringValue(); } },
                { "filters", n => { Filters = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestFilters>(global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestFilters.CreateFromDiscriminatorValue); } },
                { "max_results", n => { MaxResults = n.GetIntValue(); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestMode>(); } },
                { "page_size", n => { PageSize = n.GetIntValue(); } },
                { "save_json", n => { SaveJson = n.GetBoolValue(); } },
                { "simple_filters", n => { SimpleFilters = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestSimpleFilters>(global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestSimpleFilters.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cursor", Cursor);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestFilters>("filters", Filters);
            writer.WriteIntValue("max_results", MaxResults);
            writer.WriteEnumValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestMode>("mode", Mode);
            writer.WriteIntValue("page_size", PageSize);
            writer.WriteBoolValue("save_json", SaveJson);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.StartFilterSearchRequestSimpleFilters>("simple_filters", SimpleFilters);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
