// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StructSubField_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "string")]
        #pragma warning disable CS1591
        String,
        #pragma warning restore CS1591
        [EnumMember(Value = "int")]
        #pragma warning disable CS1591
        Int,
        #pragma warning restore CS1591
        [EnumMember(Value = "float")]
        #pragma warning disable CS1591
        Float,
        #pragma warning restore CS1591
        [EnumMember(Value = "bool")]
        #pragma warning disable CS1591
        Bool,
        #pragma warning restore CS1591
        [EnumMember(Value = "dict")]
        #pragma warning disable CS1591
        Dict,
        #pragma warning restore CS1591
    }
}
