// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>
    /// Response model for workflow run list items.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowRunResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Per-block detail; usually null in list responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponseBlocks? Blocks { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponseBlocks Blocks { get; set; }
#endif
        /// <summary>Number of blocks in the workflow at run time.</summary>
        public int? BlocksCount { get; set; }
        /// <summary>Timestamp when execution finished.</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>Timestamp when the record was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Total run duration in milliseconds.</summary>
        public int? DurationMs { get; set; }
        /// <summary>Error message if the operation failed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>Job (run) identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JobId { get; set; }
#nullable restore
#else
        public string JobId { get; set; }
#endif
        /// <summary>Aggregate run metrics (rows in/out, costs, etc.).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponseMetricsProperty? Metrics { get; set; }
#nullable restore
#else
        public global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponseMetricsProperty Metrics { get; set; }
#endif
        /// <summary>Timestamp when the run was enqueued.</summary>
        public DateTimeOffset? QueuedAt { get; set; }
        /// <summary>Timestamp when execution started.</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>Current status (e.g. queued, running, completed, failed).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Short reason explaining the current status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusReason { get; set; }
#nullable restore
#else
        public string StatusReason { get; set; }
#endif
        /// <summary>Current authoring step from the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Step { get; set; }
#nullable restore
#else
        public string Step { get; set; }
#endif
        /// <summary>Timestamp when the record was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>User who created the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>Workflow identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>Workflow name at the time of the run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowName { get; set; }
#nullable restore
#else
        public string WorkflowName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponse"/> and sets the default values.
        /// </summary>
        public WorkflowRunResponse()
        {
            AdditionalData = new Dictionary<string, object>();
            BlocksCount = 0;
            WorkflowName = "Untitled Workflow";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blocks", n => { Blocks = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponseBlocks>(global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponseBlocks.CreateFromDiscriminatorValue); } },
                { "blocks_count", n => { BlocksCount = n.GetIntValue(); } },
                { "completed_at", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "duration_ms", n => { DurationMs = n.GetIntValue(); } },
                { "error_message", n => { ErrorMessage = n.GetStringValue(); } },
                { "job_id", n => { JobId = n.GetStringValue(); } },
                { "metrics", n => { Metrics = n.GetObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponseMetricsProperty>(global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponseMetricsProperty.CreateFromDiscriminatorValue); } },
                { "queued_at", n => { QueuedAt = n.GetDateTimeOffsetValue(); } },
                { "started_at", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "status_reason", n => { StatusReason = n.GetStringValue(); } },
                { "step", n => { Step = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
                { "workflow_id", n => { WorkflowId = n.GetStringValue(); } },
                { "workflow_name", n => { WorkflowName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponseBlocks>("blocks", Blocks);
            writer.WriteIntValue("blocks_count", BlocksCount);
            writer.WriteDateTimeOffsetValue("completed_at", CompletedAt);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteIntValue("duration_ms", DurationMs);
            writer.WriteStringValue("error_message", ErrorMessage);
            writer.WriteStringValue("job_id", JobId);
            writer.WriteObjectValue<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowRunResponseMetricsProperty>("metrics", Metrics);
            writer.WriteDateTimeOffsetValue("queued_at", QueuedAt);
            writer.WriteDateTimeOffsetValue("started_at", StartedAt);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("status_reason", StatusReason);
            writer.WriteStringValue("step", Step);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteStringValue("workflow_id", WorkflowId);
            writer.WriteStringValue("workflow_name", WorkflowName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
