// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Models
{
    /// <summary>`global` for the curated catalog, `org` for a template owned by your organization.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkflowTemplateScope
    {
        [EnumMember(Value = "global")]
        #pragma warning disable CS1591
        Global,
        #pragma warning restore CS1591
        [EnumMember(Value = "org")]
        #pragma warning disable CS1591
        Org,
        #pragma warning restore CS1591
    }
}
