// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Search.Lookalike.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \search\lookalike\{taskId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTaskItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Search.Lookalike.Item.WithTaskItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTaskItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/lookalike/{taskId}{?include_analysis*,include_filters*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Search.Lookalike.Item.WithTaskItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTaskItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/lookalike/{taskId}{?include_analysis*,include_filters*}", rawUrl)
        {
        }
        /// <summary>
        /// Poll lookalike progress and return generated filters on completion.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet402Response">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet409Response">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet500Response">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet502Response">When receiving a 502 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet503Response">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet504Response">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Search.Lookalike.Item.WithTaskItemRequestBuilder.WithTaskItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Search.Lookalike.Item.WithTaskItemRequestBuilder.WithTaskItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet401Response.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet402Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet403Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet404Response.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet409Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet500Response.CreateFromDiscriminatorValue },
                { "502", global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet502Response.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet503Response.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusEndpointSearchLookalikeTaskIdGet504Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusResponse>(requestInfo, global::Soenneker.Sixtyfour.OpenApiClient.Models.LookalikeSearchStatusResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Poll lookalike progress and return generated filters on completion.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Search.Lookalike.Item.WithTaskItemRequestBuilder.WithTaskItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Search.Lookalike.Item.WithTaskItemRequestBuilder.WithTaskItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Search.Lookalike.Item.WithTaskItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sixtyfour.OpenApiClient.Search.Lookalike.Item.WithTaskItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sixtyfour.OpenApiClient.Search.Lookalike.Item.WithTaskItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Poll lookalike progress and return generated filters on completion.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithTaskItemRequestBuilderGetQueryParameters 
        {
            [QueryParameter("include_analysis")]
            public bool? IncludeAnalysis { get; set; }
            [QueryParameter("include_filters")]
            public bool? IncludeFilters { get; set; }
        }
    }
}
#pragma warning restore CS0618
