// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Models;
using Soenneker.Sixtyfour.OpenApiClient.Webhooks.SigningSecret.Roll;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Webhooks.SigningSecret
{
    /// <summary>
    /// Builds and executes requests for operations under \webhooks\signing-secret
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SigningSecretRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The roll property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Webhooks.SigningSecret.Roll.RollRequestBuilder Roll
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Webhooks.SigningSecret.Roll.RollRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Webhooks.SigningSecret.SigningSecretRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SigningSecretRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks/signing-secret", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Webhooks.SigningSecret.SigningSecretRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SigningSecretRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks/signing-secret", rawUrl)
        {
        }
        /// <summary>
        /// Revoke the active signing secret for the org.After this call, webhooks are delivered unsigned until a new secret iscreated.  This is intentional — we do not silently downgrade withoutthe customer taking an explicit action.Args:    auth: Injected auth context.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Return metadata for the org&apos;s active signing secret, or null if none exists.Never returns plaintext or raw bytes.Args:    auth: Injected auth context.Returns:    Optional[SigningSecretMetaResponse]: Metadata, or null.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SigningSecretMetaResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.SigningSecretMetaResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.SigningSecretMetaResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Sixtyfour.OpenApiClient.Models.SigningSecretMetaResponse>(requestInfo, global::Soenneker.Sixtyfour.OpenApiClient.Models.SigningSecretMetaResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Mint a new signing secret for the org.The plaintext value is returned exactly once in this response.After this call, only the preview (``sk_whsec_••••…&lt;last4&gt;``) isever shown again. There is no reveal endpoint.Any existing active secret is revoked immediately before the new oneis inserted.  Use the ``/roll`` endpoint if you need an overlap window.Args:    auth: Injected auth context.Returns:    CreateSigningSecretResponse: Plaintext and metadata.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.CreateSigningSecretResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.CreateSigningSecretResponse?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.CreateSigningSecretResponse> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Sixtyfour.OpenApiClient.Models.CreateSigningSecretResponse>(requestInfo, global::Soenneker.Sixtyfour.OpenApiClient.Models.CreateSigningSecretResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Revoke the active signing secret for the org.After this call, webhooks are delivered unsigned until a new secret iscreated.  This is intentional — we do not silently downgrade withoutthe customer taking an explicit action.Args:    auth: Injected auth context.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Return metadata for the org&apos;s active signing secret, or null if none exists.Never returns plaintext or raw bytes.Args:    auth: Injected auth context.Returns:    Optional[SigningSecretMetaResponse]: Metadata, or null.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Mint a new signing secret for the org.The plaintext value is returned exactly once in this response.After this call, only the preview (``sk_whsec_••••…&lt;last4&gt;``) isever shown again. There is no reveal endpoint.Any existing active secret is revoked immediately before the new oneis inserted.  Use the ``/roll`` endpoint if you need an overlap window.Args:    auth: Injected auth context.Returns:    CreateSigningSecretResponse: Plaintext and metadata.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Webhooks.SigningSecret.SigningSecretRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sixtyfour.OpenApiClient.Webhooks.SigningSecret.SigningSecretRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sixtyfour.OpenApiClient.Webhooks.SigningSecret.SigningSecretRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
