// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Templates.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \templates\{templateKey}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTemplateKeyItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Templates.Item.WithTemplateKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTemplateKeyItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/templates/{templateKey}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Templates.Item.WithTemplateKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTemplateKeyItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/templates/{templateKey}", rawUrl)
        {
        }
        /// <summary>
        /// Return one catalog template, e.g. ``/templates/personal-email-enrichment``.Accepts the slug or a uuid, so links minted before slug addressing keep resolving.A key carrying a namespace (``&lt;org_id&gt;:&lt;slug&gt;``) is a 404 rather than a redirect:this route serves the catalog, and an org&apos;s template is not reachable without acredential — including for an org whose id happens to look like ours.An internal-only template is a 404, not a 403, so this cannot enumerate them.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowTemplate"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetTemplateTemplatesTemplateKeyGet400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetTemplateTemplatesTemplateKeyGet401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetTemplateTemplatesTemplateKeyGet403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetTemplateTemplatesTemplateKeyGet500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowTemplate?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowTemplate> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Sixtyfour.OpenApiClient.Models.GetTemplateTemplatesTemplateKeyGet400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Sixtyfour.OpenApiClient.Models.GetTemplateTemplatesTemplateKeyGet401Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Sixtyfour.OpenApiClient.Models.GetTemplateTemplatesTemplateKeyGet403Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Sixtyfour.OpenApiClient.Models.GetTemplateTemplatesTemplateKeyGet500Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowTemplate>(requestInfo, global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowTemplate.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Return one catalog template, e.g. ``/templates/personal-email-enrichment``.Accepts the slug or a uuid, so links minted before slug addressing keep resolving.A key carrying a namespace (``&lt;org_id&gt;:&lt;slug&gt;``) is a 404 rather than a redirect:this route serves the catalog, and an org&apos;s template is not reachable without acredential — including for an org whose id happens to look like ours.An internal-only template is a 404, not a 403, so this cannot enumerate them.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Templates.Item.WithTemplateKeyItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sixtyfour.OpenApiClient.Templates.Item.WithTemplateKeyItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sixtyfour.OpenApiClient.Templates.Item.WithTemplateKeyItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
