// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Models;
using Soenneker.Sixtyfour.OpenApiClient.Workflows.Blocks;
using Soenneker.Sixtyfour.OpenApiClient.Workflows.Cancel;
using Soenneker.Sixtyfour.OpenApiClient.Workflows.Create_workflow;
using Soenneker.Sixtyfour.OpenApiClient.Workflows.Delete_workflow;
using Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive;
using Soenneker.Sixtyfour.OpenApiClient.Workflows.Item;
using Soenneker.Sixtyfour.OpenApiClient.Workflows.Run;
using Soenneker.Sixtyfour.OpenApiClient.Workflows.Runs;
using Soenneker.Sixtyfour.OpenApiClient.Workflows.Update_workflow;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Workflows
{
    /// <summary>
    /// Builds and executes requests for operations under \workflows
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The blocks property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Blocks.BlocksRequestBuilder Blocks
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Blocks.BlocksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cancel property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The create_workflow property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Create_workflow.Create_workflowRequestBuilder Create_workflow
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Create_workflow.Create_workflowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The delete_workflow property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Delete_workflow.Delete_workflowRequestBuilder Delete_workflow
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Delete_workflow.Delete_workflowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The interactive property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive.InteractiveRequestBuilder Interactive
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Interactive.InteractiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The run property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Run.RunRequestBuilder Run
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runs property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Runs.RunsRequestBuilder Runs
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Runs.RunsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update_workflow property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Update_workflow.Update_workflowRequestBuilder Update_workflow
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Update_workflow.Update_workflowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Sixtyfour.OpenApiClient.workflows.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Item.WithWorkflow_ItemRequestBuilder"/></returns>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Item.WithWorkflow_ItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("workflow_id", position);
                return new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.Item.WithWorkflow_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Workflows.WorkflowsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkflowsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Workflows.WorkflowsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkflowsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows", rawUrl)
        {
        }
        /// <summary>
        /// List all workflows for the authenticated organization.Returns a lightweight list of workflows without workflow_definition.Use GET /workflows/{workflow_id} to retrieve the full workflow with its definition.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowResponse>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowResponse>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowResponse>(requestInfo, global::Soenneker.Sixtyfour.OpenApiClient.Models.WorkflowResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// List all workflows for the authenticated organization.Returns a lightweight list of workflows without workflow_definition.Use GET /workflows/{workflow_id} to retrieve the full workflow with its definition.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Workflows.WorkflowsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sixtyfour.OpenApiClient.Workflows.WorkflowsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sixtyfour.OpenApiClient.Workflows.WorkflowsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
