// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.OrgChart.FilterCapabilities;
using Soenneker.Sixtyfour.OpenApiClient.OrgChart.FindPeople;
using Soenneker.Sixtyfour.OpenApiClient.OrgChart.Full;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.OrgChart
{
    /// <summary>
    /// Builds and executes requests for operations under \org-chart
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrgChartRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The filterCapabilities property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.OrgChart.FilterCapabilities.FilterCapabilitiesRequestBuilder FilterCapabilities
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.OrgChart.FilterCapabilities.FilterCapabilitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The findPeople property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.OrgChart.FindPeople.FindPeopleRequestBuilder FindPeople
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.OrgChart.FindPeople.FindPeopleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The full property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.OrgChart.Full.FullRequestBuilder Full
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.OrgChart.Full.FullRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.OrgChart.OrgChartRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrgChartRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/org-chart", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.OrgChart.OrgChartRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrgChartRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/org-chart", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
