// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Google.Sheets.AccessToken;
using Soenneker.Sixtyfour.OpenApiClient.Google.Sheets.Connect;
using Soenneker.Sixtyfour.OpenApiClient.Google.Sheets.Status;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Google.Sheets
{
    /// <summary>
    /// Builds and executes requests for operations under \google\sheets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SheetsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accessToken property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Google.Sheets.AccessToken.AccessTokenRequestBuilder AccessToken
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Google.Sheets.AccessToken.AccessTokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The connect property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Google.Sheets.Connect.ConnectRequestBuilder Connect
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Google.Sheets.Connect.ConnectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Soenneker.Sixtyfour.OpenApiClient.Google.Sheets.Status.StatusRequestBuilder Status
        {
            get => new global::Soenneker.Sixtyfour.OpenApiClient.Google.Sheets.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Google.Sheets.SheetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SheetsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/google/sheets", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Google.Sheets.SheetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SheetsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/google/sheets", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
