// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Search.Export
{
    /// <summary>
    /// Builds and executes requests for operations under \search\export
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExportRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Search.Export.ExportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/export", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Search.Export.ExportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/export", rawUrl)
        {
        }
        /// <summary>
        /// Export search results as a CSV file. Poll /search/status/{task_id} for a presigned download URL when complete.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SaveSearchResponse"/></returns>
        /// <param name="body">Request to export search results as CSV.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost402Response">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost409Response">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost500Response">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost502Response">When receiving a 502 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost503Response">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost504Response">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.SaveSearchResponse?> PostAsync(global::Soenneker.Sixtyfour.OpenApiClient.Models.SaveSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sixtyfour.OpenApiClient.Models.SaveSearchResponse> PostAsync(global::Soenneker.Sixtyfour.OpenApiClient.Models.SaveSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost401Response.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost402Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost403Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost404Response.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost409Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost500Response.CreateFromDiscriminatorValue },
                { "502", global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost502Response.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost503Response.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Sixtyfour.OpenApiClient.Models.SearchExportEndpointSearchExportPost504Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Sixtyfour.OpenApiClient.Models.SaveSearchResponse>(requestInfo, global::Soenneker.Sixtyfour.OpenApiClient.Models.SaveSearchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Export search results as a CSV file. Poll /search/status/{task_id} for a presigned download URL when complete.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request to export search results as CSV.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Sixtyfour.OpenApiClient.Models.SaveSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Sixtyfour.OpenApiClient.Models.SaveSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Search.Export.ExportRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sixtyfour.OpenApiClient.Search.Export.ExportRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sixtyfour.OpenApiClient.Search.Export.ExportRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
