// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Monitors.Item.Snapshots.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \monitors\{monitorId}\snapshots\{asOf}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAsOfItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Monitors.Item.Snapshots.Item.WithAsOfItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAsOfItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/monitors/{monitorId}/snapshots/{asOf}{?limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Monitors.Item.Snapshots.Item.WithAsOfItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAsOfItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/monitors/{monitorId}/snapshots/{asOf}{?limit*}", rawUrl)
        {
        }
        /// <summary>
        /// One snapshot as a CSV: a row per subject, watched fields as columns.`as_of` is a timestamp from /snapshots, or `latest` for the present.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetMonitorSnapshotEndpointMonitorsMonitorIdSnapshotsAsOfGet400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetMonitorSnapshotEndpointMonitorsMonitorIdSnapshotsAsOfGet401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetMonitorSnapshotEndpointMonitorsMonitorIdSnapshotsAsOfGet403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetMonitorSnapshotEndpointMonitorsMonitorIdSnapshotsAsOfGet500Response">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Sixtyfour.OpenApiClient.Models.GetMonitorSnapshotEndpointMonitorsMonitorIdSnapshotsAsOfGet503Response">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Monitors.Item.Snapshots.Item.WithAsOfItemRequestBuilder.WithAsOfItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Monitors.Item.Snapshots.Item.WithAsOfItemRequestBuilder.WithAsOfItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Sixtyfour.OpenApiClient.Models.GetMonitorSnapshotEndpointMonitorsMonitorIdSnapshotsAsOfGet400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Sixtyfour.OpenApiClient.Models.GetMonitorSnapshotEndpointMonitorsMonitorIdSnapshotsAsOfGet401Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Sixtyfour.OpenApiClient.Models.GetMonitorSnapshotEndpointMonitorsMonitorIdSnapshotsAsOfGet403Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Sixtyfour.OpenApiClient.Models.HttpValidationError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Sixtyfour.OpenApiClient.Models.GetMonitorSnapshotEndpointMonitorsMonitorIdSnapshotsAsOfGet500Response.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Sixtyfour.OpenApiClient.Models.GetMonitorSnapshotEndpointMonitorsMonitorIdSnapshotsAsOfGet503Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// One snapshot as a CSV: a row per subject, watched fields as columns.`as_of` is a timestamp from /snapshots, or `latest` for the present.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Monitors.Item.Snapshots.Item.WithAsOfItemRequestBuilder.WithAsOfItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sixtyfour.OpenApiClient.Monitors.Item.Snapshots.Item.WithAsOfItemRequestBuilder.WithAsOfItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Monitors.Item.Snapshots.Item.WithAsOfItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sixtyfour.OpenApiClient.Monitors.Item.Snapshots.Item.WithAsOfItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sixtyfour.OpenApiClient.Monitors.Item.Snapshots.Item.WithAsOfItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// One snapshot as a CSV: a row per subject, watched fields as columns.`as_of` is a timestamp from /snapshots, or `latest` for the present.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithAsOfItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Only the first rows, for a preview. Omitted, the whole table.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
        }
    }
}
#pragma warning restore CS0618
