// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sixtyfour.OpenApiClient.Me.SlackLinks.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Sixtyfour.OpenApiClient.Me.SlackLinks.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \me\slack-links\{slackTeamId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSlackTeamItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Sixtyfour.OpenApiClient.me.slackLinks.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Me.SlackLinks.Item.Item.WithSlackUserItemRequestBuilder"/></returns>
        public global::Soenneker.Sixtyfour.OpenApiClient.Me.SlackLinks.Item.Item.WithSlackUserItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("slackUserId", position);
                return new global::Soenneker.Sixtyfour.OpenApiClient.Me.SlackLinks.Item.Item.WithSlackUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Me.SlackLinks.Item.WithSlackTeamItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSlackTeamItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me/slack-links/{slackTeamId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sixtyfour.OpenApiClient.Me.SlackLinks.Item.WithSlackTeamItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSlackTeamItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me/slack-links/{slackTeamId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
